### ISSUE TITLE
[TASK] Develop functions to operate the switch

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maoctrl#2]
### What is the goal?
Complete the implementation of the following features
- initialize
- finalize
- start
- halt

### Why is the task necessary?
To operate the switch

## Todo
- [ ] Implement the function to initialize
  - [ ] Format of the request to setup (switching order, etc.)
- [x] Implement the function to finalize
- [x] Implement the function to start
- [x] Implement the function to halt

## Completion condition
Merge PR
