### ISSUE TITLE
[TASK] Develop functions to operate the correlator

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maoctrl#3]
### What is the goal?
Complete the implementation of the following features
- initialize
- finalize
- start
- halt

### Why is the task necessary?
To operate the correlator

## Todo
- [x] Implement the function to initialize
  - [ ] Find out items what the function need
- [x] Implement the function to finalize
- [x] Implement the function to start
  - [ ] Format of the request to start (start time, end time, etc.)
- [x] Implement the function to halt

## Completion condition
Merge PR
