### ISSUE TITLE
[SPRINT] Apr 4 2019 → Apr 8 2019 - Release version 1.0

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maoctrl#5]
## Sprint Goal
Please write issues to do as follows::
- [ ] #2 - Develop functions to operate the switch
- [x] #3 - Develop functions to operate the correlator
- [x] #4 - Confirm the specification of the API
